config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get '/about-me', to: 'pages#about_me'
  get '/projects', to: 'pages#project'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_me
  end

  def project
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Florian Guerin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body data-controller="contact">
   <%# <% unless params[:controller] == "pages" && params[:action] == "home" %>
      <%= render "shared/navbar" %>
    <%# end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about_me.html.erb
<div class="container" data-controller="about">
  <div class="img-container">
    <%= image_tag "portrait.png" %>
  </div>
  <div class="my-4">
    <%= render "shared/professional_experiences" %>
  </div>
  <div class="my-5">
    <%= render "shared/education" %>
  </div>
  <div class="my-5">
    <%= render "shared/skills" %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="d-flex">
    <div>
      <h1>Hey ! Iam Florian</h1>
    </div>
    <div class="portrait">
      <%= image_tag "portrait-color.png" %>
    </div>
  </div>
</div>

app/views/pages/project.html.erb
<div class="container">
  <div class="container-project">
    <div class="wasteless-img">
      <%= link_to "https://www.waste-less.me/users/sign_in", target: :_blank do %>
        <%= image_tag "wasteless.png" %>
      <% end %>
    </div>
    <div class="project-card">
      <div class="title-project">
        <h2>WASTELESS</h2>
      </div>
      <div class="description-project">
        <%= render "shared/wasteless" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_amenitiz.html.erb
<ul>
  <li>
    <p>
      Onboard new customers by assisting them in setting up the Amenitiz
      account, connections, and training on the system via phone calls and
      screen sharing calls.
    </p>
  </li>
  <li>
    <p>
      Ensure proper utilization of Amenitiz to maximize the use of the tool.
    </p>
  </li>
  <li>
    <p>
      Help the client to correctly set up their account and assist them during the
      customer journey
    </p>
  </li>
  <li>
    <p>
      Gather customer feedback regarding possible bugs, improvements, and
      new functionalities, passing it along to the Product team.
    </p>
  </li>
  <li>
    <p>
      Work with the other departments (Sales, Support, Product, etc.) to
      maximize customer value.
    </p>
  </li>
</ul>
<div class="time-location">
  <p>01/2022 - 10-2022   Barcelona, Spain</p>
</div>

app/views/shared/_contact.html.erb
<%# <i class="fa-regular fa-circle-xmark" data-action="click->contact#close"></i> %>
<p>Email: guerinflorian02@gmail.com</p>
<p>Phone: +33 638724998</p>
<p>Linkedin: <%= link_to "Florian Guerin", "https://www.linkedin.com/in/florian-guerin-8b1091112/", target: :_blank %></p>
<p>GitHub: <%= link_to "FlorianG2", "https://github.com/FlorianG2", target: :_blank %></p>

app/views/shared/_education.html.erb
<div class="title">
  <h2>EDUCATION</h2>
</div>
<div class="d-flex flex-row-reverse">
  <div class="companies-container">
    <div class="company-card first-card" >
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Web Development</h4>
        <p>Le Wagon</p>
      </div>
      <div class="time-location">
        <p>04/2023 - 06-2023   Barcelona, Spain</p>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Master II Event Marketing</h4>
        <p>INSEEC U Business school</p>
      </div>
      <div class="time-location">
        <p>09/2018 - 06/2019   Lyon, France</p>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Master I Luxury</h4>
        <p>INSEEC U Business school</p>
      </div>
      <div class="time-location">
        <p>09/2017 - 06/2018   Chambéry, France</p>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Bachelor Degree in Engineering</h4>
        <p>IUT Lyon 1</p>
      </div>
      <div class="time-location">
        <p>09/2015 - 06/2016   Lyon, France</p>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>DUT Mechanical Engineering &
            Production
        </h4>
        <p>IUT Lyon 1</p>
      </div>
      <div class="time-location">
        <p>09/2013 - 06-2015   Lyon, France</p>
      </div>
    </div>
  </div>
  <div class="img-container">
    <%#= image_tag "portrait.png" %>
  </div>
</div>

app/views/shared/_essity.html.erb
<ul>
  <li>
    <p>
      Plan and schedule transports according to business and legal rules,
      scope for domestic and international shipments (outbound perspective)
    </p>
  </li>
  <li>
    <p>
      Ensure master data integration on TMS
    </p>
  </li>
  <li>
    <p>
      Manage any unrouteable issue during the optimization process within the
      expected timelines
    </p>
  </li>
  <li>
    <p>
      Conduct any communication with Customer Care /SCP or Sites related
      with daily operations activities
    </p>
  </li>
</ul>
<div class="time-location">
  <p>11/2022 - 03-2023   Barcelona, Spain</p>
</div>

app/views/shared/_first_version_home.html.erb
<div data-controller="home">
  <div class="bg-gray home-card">
    <div>
      <span class="typed" id="welcome"></span>
    </div>
    <div>
      <span class="typed" id="name"></span>
    </div>
    <div>
      <span class="typed" id="developer"></span>
    </div>
  </div>
  <div class="discover d-none" data-home-target="discover">
    <%= link_to 'Enter', about_me_path, class:"discover-btn" %>
  </div>
</div>

  <!-- Load library from the CDN -->
  <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>

  <!-- Setup and start animation! -->
  <script>
    var typed = new Typed('#welcome', {
      strings: ['Welcome to my portfolio'],
      typeSpeed: 50,
    });
    var typed = new Typed('#name', {
      strings: ['My name is Florian'],
      typeSpeed: 50,
      startDelay: 1600,
    });
    var typed = new Typed('#developer', {
      strings: ['Full Stack Developer'],
      typeSpeed: 50,
      startDelay: 3000,
    });
  </script>

app/views/shared/_le_wagon.html.erb
<ul>
  <li>
    <p>
     Assisted students at Le Wagon in their learning journey, fostering a positive and motivating environment to encourage a passion for coding.
    </p>
  </li>
  <li>
    <p>
      Supported lead instructors in delivering high-quality coding education to a diverse cohort of students, providing guidance and feedback during coding exercises and projects.
    </p>
  </li>
</ul>
<div class="time-location">
  <p>07/2023 - 08-2023   Barcelona, Spain</p>
</div>

app/views/shared/_mingret.html.erb
<ul>
  <li>
    <p>
      Customer Relationship Management: Build and maintain strong
      relationships with international customers, understand their needs, and
      provide appropriate technical solutions.
    </p>
  </li>
  <li>
    <p>
      Technical Support: Provide technical support and guidance to customers
      during the sales process, addressing their technical inquiries, and assisting with product implementation.
    </p>
  </li>
</ul>
<div class="time-location">
  <p>01/2021 - 12-2021   Mâcon, France</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="menu-navbar">
    <div class="link">
      <%= link_to "About me", root_path %>
    </div>
    <div class="link">
      <%= link_to "Projects", projects_path %>
    </div>
  </div>
  <div class="btn-navbar">
    <div class="link" data-action="click->contact#popup">
      <p id="btn-contact">Contact me</p>
    </div>
  </div>
</div>
<div class="popup d-none" data-contact-target="info">
  <%= render "shared/contact" %>
</div>

app/views/shared/_professional_experiences.html.erb
<div class="title">
  <h2>PROFESSIONAL EXPERIENCES</h2>
</div>
<div class="d-flex flex-row-reverse">
  <div class="companies-container">
    <div class="company-card first-card" >
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Teacher Assistant</h4>
        <p>Le Wagon</p>
      </div>
      <div class="details-card">
        <%= render "shared/le_wagon" %>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Transport Planner</h4>
        <p>Essity</p>
      </div>
      <div class="d-none details-card">
        <%= render "shared/essity" %>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Customer Onboarding Specialist</h4>
        <p>Amenitiz</p>
      </div>
      <div class="d-none details-card">
        <%= render "shared/amenitiz" %>
      </div>
    </div>
    <div class="company-card">
      <div class="company-card-title" data-action="click->about#dropdown">
        <h4>Technical commercial Engineer</h4>
        <p>Mingret</p>
      </div>
      <div class="d-none details-card">
        <%= render "shared/mingret" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_skills.html.erb
<div class="title">
    <h2>SKILLS</h2>
</div>
<div class="d-flex flex-row-reverse">
  <div class="companies-container">
    <div class="grid-skills">
      <div class="skill-details">
        <p>RUBY</p>
        <p>HTML</p>
        <p>CSS</p>
        <p>JAVASCRIPT</p>
      </div>
      <div class="skill-details">
        <p>RUBY ON RAILS</p>
        <p>VS CODE</p>
        <p>FIGMA</p>
        <p>HEROKU</p>
      </div>
      <div class="skill-details">
        <p>TEAM WORK</p>
        <p>CROSS-DEPARTMENT</p>
        <p>WEBPACK</p>
        <p>HUBSPOT</p>
      </div>
    </div>
    <div class="title">
      <h2>LANGUAGES</h2>
    </div>
    <div class="language">
      <h4>French</h4>
      <p>Native</p>
      <div class="ranking">
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
      </div>
    </div>
    <div class="language">
      <h4>English</h4>
      <p>Advanced</p>
       <div class="ranking">
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-regular fa-circle"></i>
      </div>
    </div>
    <div class="language">
      <h4>Spanish</h4>
      <p>Intermediate</p>
       <div class="ranking">
        <i class="fa-solid fa-circle"></i>
        <i class="fa-solid fa-circle"></i>
        <i class="fa-regular fa-circle"></i>
        <i class="fa-regular fa-circle"></i>
        <i class="fa-regular fa-circle"></i>
      </div>
    </div>
  </div>
  <div class="img-container">
    <%#= image_tag "portrait.png" %>
  </div>
</div>

app/views/shared/_wasteless.html.erb
<p>
  Rails application to keep track of what you have in your 'inventory' (food you have at home) and its expiration date. <br>
  <br> At the moment this uses an estimate for a given (for now arbitrary) food-category, e.g. a tomato gets its expiration date from the vegetable category (7 days). <br>
  <br> Select ingredients to use and get an overview of recipes matching your selection. <br>
  <br> Generate a shopping list from a recipe (matching your existing ingredients and removing from inventory & adding missing ingredients to shopping list). <br>
  <br> Add bought ingredients directly from shopping list or adding manually (using either dropdown-search or barcode scan)
</p>
<p>
  <br>You will need to log In to enter the web app. <br>
  <br>You can use this email: florian@wasteless.es
  <br> With this password: 123456
</p>